
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Name','com_staff.name','{"special":{"dbtable":"#__staff_name","key":"id","type":"Name","prefix":"StaffTable"}}', '{"formFile":"administrator\/components\/com_staff\/models\/forms\/name.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"position","targetTable":"#__staff_position","targetColumn":"name","displayColumn":"name"},{"sourceColumn":"department","targetTable":"#__staff_department","targetColumn":"name","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_staff.name')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Name', 
	`table` = '{"special":{"dbtable":"#__staff_name","key":"id","type":"Name","prefix":"StaffTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_staff\/models\/forms\/name.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"position","targetTable":"#__staff_position","targetColumn":"name","displayColumn":"name"},{"sourceColumn":"department","targetTable":"#__staff_department","targetColumn":"name","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_staff.name');
